In [1]:
import tensorflow as tf

In [9]:
#Cost 최적화
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost,feed_dict={X: x_data, Y: y_data} ))
    # test & one-hot encoding
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                         [1, 3, 4, 3],
                                         [1, 1, 0, 1]]})
    print(all, sess.run(tf.arg_max(all, 1)))

0 3.5972507
200 0.5998285
400 0.4940977
600 0.40104905
800 0.31014735
1000 0.23918802
1200 0.2163018
1400 0.19750485
1600 0.1816133
1800 0.16800731
2000 0.15623353
Instructions for updating:
Use `tf.math.argmax` instead
[[1.0449837e-02 9.8953956e-01 1.0571890e-05]
 [7.9378808e-01 1.8091002e-01 2.5301896e-02]
 [1.2829951e-08 3.5606485e-04 9.9964392e-01]] [1 0 2]
