In [1]:
import tensorflow as tf

In [2]:
# train and test data
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [11]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
# when learning_rate = 1.5 or 1e-10
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [12]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 3.829702 [[ 0.14378372  1.4282844   0.35446805]
 [-0.6593142  -0.27362645  0.54000425]
 [ 0.66995263  0.6208506  -0.20361897]]
1 1.7359986 [[ 0.16597195  1.4036977   0.35686654]
 [-0.5054967  -0.35973394  0.4722942 ]
 [ 0.8211283   0.52333236 -0.25727633]]
2 1.1257414 [[ 0.17435506  1.3947146   0.35746652]
 [-0.41276926 -0.37493786  0.3947707 ]
 [ 0.90173584  0.5048908  -0.3194423 ]]
3 1.0091369 [[ 0.1627219   1.3924791   0.37133515]
 [-0.42479265 -0.3595596   0.39141583]
 [ 0.8746779   0.5264648  -0.31395844]]
4 1.0001502 [[ 0.15788792  1.3838344   0.38481382]
 [-0.40232646 -0.37626374  0.3856538 ]
 [ 0.88401735  0.51406574 -0.3108988 ]]
5 0.99228215 [[ 0.14821744  1.3806669   0.39765188]
 [-0.40513504 -0.3655228   0.37772143]
 [ 0.86712646  0.5295508  -0.30949298]]
6 0.98490596 [[ 0.1424397   1.3732909   0.4108056 ]
 [-0.38851368 -0.3758952   0.37147245]
 [ 0.87110114  0.52291    -0.30682683]]
7 0.97795963 [[ 0.13370648  1.3692737   0.4235561 ]
 [-0.38755795 -0.3694454   0.36406696

135 0.62954104 [[-0.5576024   0.97965664  1.5044831 ]
 [-0.03188802 -0.2172241  -0.14382403]
 [ 0.76962566  0.53804857 -0.22048977]]
136 0.6284828 [[-0.5618296   0.9783632   1.5100038 ]
 [-0.03110423 -0.21648397 -0.14534792]
 [ 0.7705275   0.53802717 -0.22137022]]
137 0.62743396 [[-0.56604594  0.9770862   1.5154972 ]
 [-0.03033253 -0.21575318 -0.1468504 ]
 [ 0.7714375   0.5380082  -0.22226131]]
138 0.6263945 [[-0.57025146  0.9758254   1.5209635 ]
 [-0.02957285 -0.21503143 -0.14833182]
 [ 0.77235544  0.53799176 -0.22316277]]
139 0.6253642 [[-0.57444626  0.9745807   1.5264031 ]
 [-0.02882491 -0.2143187  -0.1497925 ]
 [ 0.77328116  0.5379776  -0.22407433]]
140 0.62434274 [[-0.57863045  0.97335184  1.5318161 ]
 [-0.02808862 -0.21361467 -0.15123281]
 [ 0.7742144   0.5379657  -0.22499575]]
141 0.62333024 [[-0.5828041   0.97213864  1.537203  ]
 [-0.02736365 -0.21291938 -0.15265307]
 [ 0.7751551   0.53795594 -0.22592676]]
142 0.62232643 [[-0.58696735  0.970941    1.5425638 ]
 [-0.02664997 -0.2

In [ ]:
#nan