In [2]:
import tensorflow as tf
import numpy as np


In [6]:
#data
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
# Non-normalized inputs
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# 입력변수들의 값 차이가 너무 커서 nan이 떠버림  

0 Cost:  321975000000.0 
Prediction:
 [[400426.3 ]
 [807374.3 ]
 [634872.  ]
 [444678.03]
 [524291.75]
 [528716.94]
 [484494.84]
 [617197.4 ]]
1 Cost:  3.5374746e+26 
Prediction:
 [[-1.3267159e+13]
 [-2.6708153e+13]
 [-2.1010340e+13]
 [-1.4728136e+13]
 [-1.7357895e+13]
 [-1.7503993e+13]
 [-1.6043016e+13]
 [-2.0425950e+13]]
2 Cost:  inf 
Prediction:
 [[4.3975789e+20]
 [8.8527779e+20]
 [6.9641610e+20]
 [4.8818397e+20]
 [5.7535090e+20]
 [5.8019350e+20]
 [5.3176742e+20]
 [6.7704562e+20]]
3 Cost:  inf 
Prediction:
 [[-1.4576369e+28]
 [-2.9343725e+28]
 [-2.3083650e+28]
 [-1.6181517e+28]
 [-1.9070782e+28]
 [-1.9231298e+28]
 [-1.7626150e+28]
 [-2.2441592e+28]]
4 Cost:  inf 
Prediction:
 [[4.8315342e+35]
 [9.7263741e+35]
 [7.6513877e+35]
 [5.3635822e+35]
 [6.3212681e+35]
 [6.3744729e+35]
 [5.8424253e+35]
 [7.4385682e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

In [14]:
# Normalized input (min-max scale)
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)
xy = min_max_scaler(xy)
print(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

[[0.9999999  0.9999999  0.         0.9999999  0.9999999 ]
 [0.70548484 0.70439545 0.9999999  0.71881775 0.83755783]
 [0.54412544 0.50274819 0.5760869  0.60646794 0.66063303]
 [0.33890349 0.3136802  0.10869564 0.4598913  0.43800914]
 [0.51435995 0.42582385 0.3043478  0.585048   0.42624397]
 [0.49556174 0.42582385 0.31521736 0.48131129 0.49276132]
 [0.11436063 0.         0.20652172 0.22007774 0.18597236]
 [0.         0.07747099 0.53260864 0.         0.        ]]


In [15]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.1247129 
Prediction:
 [[ 1.2176749 ]
 [ 0.412376  ]
 [ 0.2922855 ]
 [ 0.18178135]
 [ 0.29525614]
 [ 0.2235604 ]
 [-0.31196055]
 [-0.4802546 ]]
1 Cost:  0.12470824 
Prediction:
 [[ 1.2176852 ]
 [ 0.41238776]
 [ 0.29229537]
 [ 0.18178901]
 [ 0.295265  ]
 [ 0.22356912]
 [-0.31195384]
 [-0.48024747]]
2 Cost:  0.1247036 
Prediction:
 [[ 1.2176955 ]
 [ 0.41239947]
 [ 0.29230517]
 [ 0.18179667]
 [ 0.29527384]
 [ 0.22357774]
 [-0.31194717]
 [-0.4802403 ]]
3 Cost:  0.12469894 
Prediction:
 [[ 1.217706  ]
 [ 0.4124113 ]
 [ 0.2923151 ]
 [ 0.18180433]
 [ 0.2952828 ]
 [ 0.22358653]
 [-0.31194046]
 [-0.48023316]]
4 Cost:  0.12469429 
Prediction:
 [[ 1.2177163 ]
 [ 0.4124232 ]
 [ 0.29232496]
 [ 0.18181199]
 [ 0.29529166]
 [ 0.22359514]
 [-0.3119338 ]
 [-0.480226  ]]
5 Cost:  0.12468963 
Prediction:
 [[ 1.2177266 ]
 [ 0.41243497]
 [ 0.2923347 ]
 [ 0.18181959]
 [ 0.29530057]
 [ 0.22360387]
 [-0.31192708]
 [-0.48021886]]
6 Cost:  0.124684975 
Prediction:
 [[ 1.217737  ]
 [ 0.4124468 ]
 [ 0.29